[project]
site_name = "Masala-Azafran"
site_description = "International recipes from an indo-hispanic kitchen."
site_author = "Jtachan"
site_url = "https://www.masalazafran.com/"
docs_dir = "recipes"

[project.extra.tags]
Beans = "beans"
Easy = "easy"
Fermented = "fermented"
Bread = "bread"
Indian = "indian"
Side-dish = "side-dish"
Vegetarian = "vegetarian"
Mexican = "mexican"
Oven = "oven"
Italian = "italian"

[project.theme]
language = "en"
features = [
    "content.footnote.tooltips",
    "content.tabs.link",
    "content.tooltips",
    "header.autohide",
    "navigation.expand",
    "navigation.footer",
    "navigation.indexes",
    "navigation.instant",
    "navigation.instant.prefetch",
    "navigation.path",
    "navigation.prune",
    "navigation.sections",
    "navigation.tabs",
    "navigation.tabs.sticky",
    "navigation.top",
    "navigation.tracking",
    "search.highlight",
    "toc.follow",
    "toc.integrate",
]
palette = [
    { scheme = "default", toggle = { icon = "lucide/sun", name = "Switch to dark mode" } },
    { scheme = "slate", toggle = { icon = "lucide/moon", name = "Switch to light mode" } },
]
